# fly.toml app configuration file generated for webdav-mp2gzg on 2024-12-10T14:53:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webdav-mp2gzg'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 6065
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
